config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "lists#index"
  get "/lists/:id/finished_yes_no", to: "lists#finished_yes_no", as: "finished_yes_no"
  get 'lists/new', to: 'lists#new'
  get 'list/:id', to: 'lists#show'
  post 'lists', to: 'lists#create'
  get 'list/:id/edit', to: 'lists#edit', as: 'edit_list'
  patch 'list/:id', to: 'lists#update'
  delete 'list/:id',to: 'lists#delete'

end

app/models/list.rb
class List < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable

    has_many :lists

    after_create :send_notification

    def send_notification
        AdminMailer.new_user(self).deliver
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #AdminMailer.new_user(self).deliver

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  before_action :authenticate_user!, only: [:create, :update, :delete]
  before_action :strong_params_lists, only: [:create, :update]
  before_action :set_list, only: [:show, :edit, :update, :destroy, :todos_featured, :finished_yes_no]

  def all_user_todos

  end

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def show
  end

  def create
    @list = List.new. strong_params_lists
    if @list.save
      redirect_to @list, notice: "Successfully created!"
    end
    render :new
  end

  def edit
  end

  def update
    if @list.update
      redirect_to root_path, notice: "Successfully Created!"
    end
    # render :show
  end

  def destroy
    @list.destroy
  end

  def finished_yes_no
    @list.toggle!(:finished)
    flash[:notice] = "You are #{@list.finished}"
    redirect_to @list
  end



  private


  def strong_params_lists
    params.require(:list).permit(:title,:content,:due_day, :finished)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TODOS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
    <div class="nav-wrapper">
      <a href = "#" class = "brand-logo" > =) DeLibro </a>
        <ul id = "nav-mobile" class = "right hide-on-med-and-down" >
            <li> My-TODOS </a></li>
            <li> Sign-out </a></li>
        </ul>
    </div>
</nav>

<% if flash[:notice] %>
  <%= flash[:notice] %>
<%end%>


<%= yield %>


<footer class="page-footer">
    <div class="footer-copyright">
            © 2015 Copyright Company
        </div>
    </div>
</footer>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list do | list | %>

    <div class = "form">
        <div class = "form-title">
            <%= list.label :title%>
            <%= list.text_field :title%>
        </div>

        <div class = "form-content">
            <%= list.label  :content %>
            <%= list.text_area :content, rows: 10, cols: 20  %>
        </div>

        <div class = "form-duday">
            <%= list.label :due_day %>
            <%= list.text_field :due_day, size: 10 %>
        </div>

        <div class = "form-save"> <%= submit_tag 'Save', class: 'btn btn-default' %> </div>
    </div>


<%end%>

app/views/lists/_list.html.erb
<div class = "list">

    <div class = "link-list"><h3><%= link_to_unless_current list.title, lists_path(list) %></h3></div>
    <div class = "due-day-list"><h3>Due Date: <%= list.due_day %></h3>

    <%= simple_format(list.content)%>
</div>

app/views/lists/edit.html.erb
<h3>Edit List</h3>
<%rende partial: "form"%>
<br/>
<div>
    <%= link_to "Back" :back, class: 'btn btn-danger'%>
</div>

app/views/lists/index.html.erb
<ul class="list-unstyled">
          <% if current_user %>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete,
                            class: 'btn btn-warning' %></li>
          <% else %>
             <li><%= link_to "Login", new_user_session_path, class: 'btn btn-success' %>
          <% end %>
</u>


<div class = "lists">
    <%@lists.each do |list|%>
      <%= render partial: "list", locals: {list: list}%>
    <%end%>
</div>

app/views/lists/new.html.erb
<%= render partial: "form" %>

app/views/lists/show.html.erb
<%= render partial: "list", object: @list %>

<div class = "list-nav">

    <%if @list.user == current_user %>

    <%= link_to "Edit List", edit_list_path(@list), class: 'btn btn-info' %>
    <%= link_to "Delete List", lists_path(@list), class: 'btn btn-danger',
            method: :delete,
            data: {confirm: "Are you sure"} %>
    <%end%>
    <%= link_to "Are you finished?", finished_yes_no_path(@list) %>
</div>